{
 "title": "Interconnect Stats",
 "tags": [ "Interconnect" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "OVHost", "query": "label_values(oneview_hostname)" },
   {
    "name": "OVInterconnect",
    "query": "label_values(oneview_interconnect)"
   },
   { "name": "OVPorts", "query": "label_values(port)" }
  ]
 },
 "panels": [
  {
   "title": "Port Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ov_port_transmit_bytes_gauge{oneview_hostname=~\"$OVHost\",port=~\"$OVPorts\",oneview_interconnect=~\"$OVInterconnect\"}",
     "legendFormat": "{{ port }} - Transmit"
    },
    {
     "expr": "ov_port_receive_bytes_gauge{oneview_hostname=~\"$OVHost\",port=~\"$OVPorts\",oneview_interconnect=~\"$OVInterconnect\"}",
     "legendFormat": "{{ port }} - Receive"
    }
   ]
  },
  {
   "title": "Transmit Utilization",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ov_port_transmit_bytes_gauge{oneview_hostname=~\"$OVHost\",port=~\"$OVPorts\",oneview_interconnect=~\"$OVInterconnect\"}",
     "legendFormat": "{{ port }} - Transmit"
    }
   ]
  },
  {
   "title": "Receive Utilization",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ov_port_receive_bytes_gauge{oneview_hostname=~\"$OVHost\",port=~\"$OVPorts\",oneview_interconnect=~\"$OVInterconnect\"}",
     "legendFormat": "{{ port }} - Receive"
    }
   ]
  },
  {
   "title": "Transmit Error",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ov_port_transmit_error_gauge{oneview_hostname=~\"$OVHost\",port=~\"$OVPorts\",oneview_interconnect=~\"$OVInterconnect\"}",
     "legendFormat": "{{ port }} - Transmit"
    }
   ]
  },
  {
   "title": "Receive Error",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ov_port_receive_error_gauge{oneview_hostname=~\"$OVHost\",port=~\"$OVPorts\",oneview_interconnect=~\"$OVInterconnect\"}",
     "legendFormat": "{{ port }} - Receive"
    }
   ]
  }
 ]
}