{
 "title": "Server Events",
 "tags": [ "Server" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "OVHost", "query": "label_values(oneview_hostname)" },
   { "name": "OVServerHardware", "query": "label_values(server_hardware)" }
  ]
 },
 "panels": [
  {
   "title": "CRITICAL ACTIVE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ov_serverhardware_critical_total{oneview_alert_type=\"Active\",oneview_hostname=~\"$OVHost\"}"
    }
   ]
  },
  {
   "title": "CRITICAL LOCKED",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "ov_serverhardware_critical_total{oneview_alert_type=\"Locked\"}"
    }
   ]
  },
  {
   "title": "CRITICAL CLEARED",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ov_serverhardware_critical_total{oneview_alert_type=\"Cleared\",oneview_hostname=~\"$OVHost\"}"
    }
   ]
  },
  {
   "title": "CRITICAL ALERTS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ov_serverhardware_critical_gauge{oneview_hostname=~\"$OVHost\",resource_name=~\"$OVServerHardware\"}",
     "legendFormat": "{{ resource_name }}"
    }
   ]
  },
  {
   "title": "CRITICAL FAILURE MESSAGE",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ov_serverhardware_critical_messages_gauge{resource_name=~\"$OVServerHardware\"}",
     "legendFormat": "{{ message }}"
    }
   ]
  }
 ]
}