{
 "title": "Server Statistics",
 "tags": [ "Server" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "OVHost", "query": "label_values(oneview_hostname)" },
   { "name": "OVServerHW", "query": "label_values(server_hardware)" }
  ]
 },
 "panels": [
  {
   "title": "Server Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ov_server_temperature_gauge{server_hardware=~\"$OVServerHW\"}",
     "legendFormat": "{{ server_hardware }}"
    }
   ]
  },
  {
   "title": "Server Average Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ov_server_avg_power_gauge{server_hardware=~\"$OVServerHW\"}",
     "legendFormat": "{{ server_hardware }}"
    }
   ]
  },
  {
   "title": "Server Peak Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ov_server_peak_power_gauge{server_hardware=~\"$OVServerHW\"}",
     "legendFormat": "{{ server_hardware }}"
    }
   ]
  }
 ]
}