{
 "title": "Server Profile Events",
 "tags": [ "ServerProfile" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "OVHost", "query": "label_values(oneview_hostname)" },
   {
    "name": "OVProfileName",
    "query": "label_values(ov_serverprofile_critical_gauge,resource_name)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CRITICAL ACTIVE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ov_serverprofile_critical_total{oneview_alert_type=\"Active\"}"
    }
   ]
  },
  {
   "title": "CRITICAL LOCKED",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "ov_serverprofile_critical_total{oneview_alert_type=\"Locked\"}"
    }
   ]
  },
  {
   "title": "CRITICAL CLEARED",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "ov_serverprofile_critical_total{oneview_alert_type=\"Cleared\"}"
    }
   ]
  },
  {
   "title": "CRITICAL ALERTS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ov_serverprofile_critical_gauge{oneview_hostname=~\"$OVHost\",resource_name=~\"$OVProfileName\"}",
     "legendFormat": "{{ resource_name }}"
    }
   ]
  },
  {
   "title": "CRITICAL FAILURE MESSAGE",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ov_serverprofile_critical_messages_gauge{resource_name=~\"$OVProfileName\"}",
     "legendFormat": "{{ message }}"
    }
   ]
  }
 ]
}