apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "prometheus.labels" . | indent 4 }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
      prometheus.io/path: /metrics
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} 
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "prometheus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
